# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86184b05bafb0ba7de0e8d06cea715519bc38a5e20b9cb6b15c5fec50234febea2e73bf244c7d82b7cd3ed3d58a24646d34b2685c039a663e61969fc66128ef5

test:
  secret_key_base: 0d29b204dc06f587566362fa94cfc23c7eab78fa21f6be5a6844bcf3d7611dc21ee47fb203b36df3abf7027ed64f1a3b3bde9d0798caa6ab3467a84720d93881

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
